version: "3.9"

services:
  projectdawnapi:
    build:
      context: .
    ports:
      - "${API_HTTP_PORT}:8080"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_VERSION=9.0
