services:
  mysql:
    image: mysql:8.0
    container_name: projectdawn-mysql
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  projectdawnapi:
    build:
      context: .
    container_name: projectdawn-api
    ports:
      - "${API_HTTP_PORT}:8080"
    depends_on:
      - mysql
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      DOTNET_RUNNING_IN_CONTAINER: "true"
      DOTNET_VERSION: "9.0"
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}

      DB_PROVIDER: ${DB_PROVIDER}
      SQLITE_PATH: ${SQLITE_PATH}

      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

volumes:
  mysql_data:
