name: Delete Failed & Cancelled Workflow Runs

on:
  workflow_dispatch:

jobs:
  delete-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Delete failed and cancelled workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # DO NOT keep by age/count
          retain_days: 0
          keep_minimum_runs: 0

          # âœ… FILTERS
          delete_run_by_conclusion_pattern: |
            failure
            cancelled
